### ISSUE TITLE
Cannot decode .rosbag files from specific dataset

### ISSUE THREAD

**Issue by biphasic** [event-driven-robotics/importRosbag#6]
Hello,
when trying to read rosbag files from this dataset: https://zenodo.org/record/4302805
I get the following error:
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-7-516b93ac85b5> in <module>
      2 
      3 importTopics = ['/dvs/camera_info']
----> 4 topics = importRosbag(filePathOrName='./data/visual_place_recognition/dvs_vpr_2020-04-27-18-13-29.bag', importTopics=importTopics)

~/anaconda3/lib/python3.7/site-packages/importRosbag/importRosbag.py in importRosbag(filePathOrName, **kwargs)
    192             print('    ' + topicKey + ' --- ' + topic['type'])
    193         return topics
--> 194     msgs = breakChunksIntoMsgs(chunks)
    195     for msg in msgs:
    196         connDict[msg['conn']]['msgs'].append(msg)

~/anaconda3/lib/python3.7/site-packages/importRosbag/importRosbag.py in breakChunksIntoMsgs(chunks)
    156             headerBytes = chunk['data'][ptr:ptr+headerLen]
    157             ptr += headerLen
--> 158             fields = unpackHeader(headerLen, headerBytes)
    159             # Read the record data
    160             dataLen = unpack('=l', chunk['data'][ptr:ptr+4])[0]

~/anaconda3/lib/python3.7/site-packages/importRosbag/messageTypes/common.py in unpackHeader(headerLen, headerBytes)
     33         #print(field)
     34         fieldSplit = field.find(b'\x3d')
---> 35         fieldName = field[:fieldSplit].decode("utf-8")
     36         fieldValue = field[fieldSplit+1:]
     37         fields[fieldName] = fieldValue

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8d in position 0: invalid start byte

Rosbags from other datasets such as http://rpg.ifi.uzh.ch/davis_data.html work great.
Do you have an idea what happened there?

**Comment by Tobias-Fischer** [comment]
Hi @biphasic - the author of this particular dataset here. I bet it is because these rosbags are compressed. I can upload some uncompressed rosbags that should not have this issue. I'll give it a go on Monday.

**Comment by biphasic** [comment]
Thank you Tobias! @simbamford Do you think decompression is something that importRosbag is going to support in the future?

**Comment by simbamford** [comment]
Hi Gregor, I'm too busy to write this at the moment, but I'd happily accept a PR.

**Comment by biphasic** [comment]
No problem, thanks for letting me know!
